name: Cloud GC

on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  gc-cloud-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: >
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN}} DIGITALOCEAN_TOKEN=${{ secrets.DIGITALOCEAN_TOKEN }} node .github/workflows/cloud-gc.js

